name: Create Release

on:
  push:
    branches:
      - release

jobs:
  build:
    name: Build production artifacts
    if: github.event.pull_request.merged == 'true'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install node modules
        run:  npm install

      - name: Build plugin
        run: npm run package

      - name: Get current package version
        uses: martinbeentjes/npm-get-version-action@v1.2.3
        env:
          PACKAGE_NAME: ${{ github.event.repository.name }}.${{ steps.package-version.outputs.current-version}}

      - name: Rename build folder
        run: mv release $PACKAGE_NAME

      - name: Zip build
        uses: montudor/action-zip@v1
        with:
          args: zip -q -r $PACKAGE_NAME.zip $PACKAGE_NAME

      - name: Create release
        run: npx semantic-release
