name: Create Release

on:
  workflow_dispatch:
  push:
    branches:
      - release

jobs:
  release:
    name: Release plugin
    permissions:
      contents: write
      issues: write
      pull-requests: write
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install node modules
        run:  npm install

      - name: Package plugin
        run: npm run package

      - name: Get current package.json version
        id: extract-version
        uses: Saionaro/extract-package-version@v1.2.1

      - name: Generate package folder name
        id: package-name
        run: echo "PACKAGE_NAME=${{ github.event.repository.name }}-${{ steps.extract-version.outputs.version }}" >> $GITHUB_OUTPUT

      - name: Rename package folder
        run: mv release ${{ steps.package-name.outputs.PACKAGE_NAME }}

      - name: Zip artifacts
        uses: montudor/action-zip@v1
        with:
          args: zip -q -r ${{ steps.package-name.outputs.PACKAGE_NAME }}.zip ${{ steps.package-name.outputs.PACKAGE_NAME }}

      - name: Create release
        run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
